name: flutter_chat_ui
description: >
  Actively maintained, community-driven chat UI implementation with an
  optional Firebase BaaS.
version: 1.6.8
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  diffutil_dart: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.1
  flutter_link_previewer: ^3.2.1
  flutter_parsed_text: ^2.2.1
  intl: ^0.18.0
  meta: ^1.9.1
  photo_view: ^0.14.0
  scroll_to_index: ^3.0.1
  url_launcher: ^6.1.11
  visibility_detector: ^0.4.0+2

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/flutter_chat_ui/assets/icon-arrow.png
    - packages/flutter_chat_ui/assets/icon-attachment.png
    - packages/flutter_chat_ui/assets/icon-delivered.png
    - packages/flutter_chat_ui/assets/icon-document.png
    - packages/flutter_chat_ui/assets/icon-error.png
    - packages/flutter_chat_ui/assets/icon-seen.png
    - packages/flutter_chat_ui/assets/icon-send.png
    - packages/flutter_chat_ui/assets/2.0x/icon-arrow.png
    - packages/flutter_chat_ui/assets/2.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/2.0x/icon-delivered.png
    - packages/flutter_chat_ui/assets/2.0x/icon-document.png
    - packages/flutter_chat_ui/assets/2.0x/icon-error.png
    - packages/flutter_chat_ui/assets/2.0x/icon-seen.png
    - packages/flutter_chat_ui/assets/2.0x/icon-send.png
    - packages/flutter_chat_ui/assets/3.0x/icon-arrow.png
    - packages/flutter_chat_ui/assets/3.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/3.0x/icon-delivered.png
    - packages/flutter_chat_ui/assets/3.0x/icon-document.png
    - packages/flutter_chat_ui/assets/3.0x/icon-error.png
    - packages/flutter_chat_ui/assets/3.0x/icon-seen.png
    - packages/flutter_chat_ui/assets/3.0x/icon-send.png
