name: flutter_chat_ui
description: >
  Actively maintained, community-driven chat UI implementation with an
  optional Firebase BaaS.
version: 1.1.9
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  diffutil_dart: ^2.0.0+1
  equatable: ^2.0.3
  flutter_chat_types: ^2.4.1
  flutter_link_previewer: ^2.2.3
  intl: ^0.17.0
  meta: ^1.3.0
  photo_view: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  assets:
    - packages/flutter_chat_ui/assets/icon-attachment.png
    - packages/flutter_chat_ui/assets/icon-delivered.png
    - packages/flutter_chat_ui/assets/icon-document.png
    - packages/flutter_chat_ui/assets/icon-error.png
    - packages/flutter_chat_ui/assets/icon-seen.png
    - packages/flutter_chat_ui/assets/icon-send.png
    - packages/flutter_chat_ui/assets/2.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/2.0x/icon-delivered.png
    - packages/flutter_chat_ui/assets/2.0x/icon-document.png
    - packages/flutter_chat_ui/assets/2.0x/icon-error.png
    - packages/flutter_chat_ui/assets/2.0x/icon-seen.png
    - packages/flutter_chat_ui/assets/2.0x/icon-send.png
    - packages/flutter_chat_ui/assets/3.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/3.0x/icon-delivered.png
    - packages/flutter_chat_ui/assets/3.0x/icon-document.png
    - packages/flutter_chat_ui/assets/3.0x/icon-error.png
    - packages/flutter_chat_ui/assets/3.0x/icon-seen.png
    - packages/flutter_chat_ui/assets/3.0x/icon-send.png
