name: flutter_chat_ui
description: Flutter Chat UI
version: 0.6.1
homepage: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types: ^2.0.1
  flutter_link_previewer: ^0.2.2
  intl: ^0.17.0
  photo_view: ^0.11.0
  universal_io: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  assets:
    - packages/flutter_chat_ui/assets/icon-attachment.png
    - packages/flutter_chat_ui/assets/icon-document.png
    - packages/flutter_chat_ui/assets/icon-read.png
    - packages/flutter_chat_ui/assets/icon-send.png
    - packages/flutter_chat_ui/assets/icon-sent.png
    - packages/flutter_chat_ui/assets/2.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/2.0x/icon-document.png
    - packages/flutter_chat_ui/assets/2.0x/icon-read.png
    - packages/flutter_chat_ui/assets/2.0x/icon-send.png
    - packages/flutter_chat_ui/assets/2.0x/icon-sent.png
    - packages/flutter_chat_ui/assets/3.0x/icon-attachment.png
    - packages/flutter_chat_ui/assets/3.0x/icon-document.png
    - packages/flutter_chat_ui/assets/3.0x/icon-read.png
    - packages/flutter_chat_ui/assets/3.0x/icon-send.png
    - packages/flutter_chat_ui/assets/3.0x/icon-sent.png
