name: flutter_chat_ui
version: 2.7.0
description: >
  Free and open-source chat SDK. Build fast, real-time apps and generative
  AI agents with a high-performance, customizable, cross-platform UI.
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  cross_cache: ^1.0.3
  diffutil_dart: ^4.0.1
  flutter:
    sdk: flutter
  flutter_chat_core: ^2.7.0
  provider: ^6.1.5
  scrollview_observer: ^1.26.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
