name: flutter_chat_ui
version: 2.11.0
description: >
  Free and open-source chat SDK. Build fast, real-time apps and generative
  AI agents with a high-performance, customizable, cross-platform UI.
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  cross_cache: ^1.1.0
  diffutil_dart: ^4.0.1
  flutter:
    sdk: flutter
  flutter_chat_core: ^2.9.0
  provider: ^6.1.5+1
  scrollview_observer: ^1.26.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
