name: flyer_chat_text_message
version: 2.5.2
description: >
  Text message package for Flutter chat apps, complementing flutter_chat_ui. #chat #ui
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_core: ^2.8.0
  gpt_markdown: ^1.1.4
  provider: ^6.1.5+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
