name: cross_cache
version: 0.0.2
description: >
  Cross-platform cache manager for Flutter using IndexedDB for web, file system
  for mobile and desktop, and Dio for network requests. #cache #indexeddb #dio
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  cross_file: ^0.3.4+2
  crypto: ^3.0.6
  dio: ^5.7.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
