name: cross_cache
version: 1.1.0
description: >
  Cross-platform cache manager for Flutter using IndexedDB for web, file system
  for mobile and desktop, and Dio for network requests. #cache #indexeddb #dio
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  cross_file: ^0.3.5+1
  crypto: ^3.0.7
  dio: ^5.9.0
  flutter:
    sdk: flutter
  idb_shim: ^2.6.7+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
