name: flutter_chat_core
version: 0.0.2
description: >
  Core package for Flutter chat apps, complementing flutter_chat_ui.
  Contains models and core functionality. #chat #ui
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
