name: flutter_chat_core
version: 0.0.3
description: >
  Core package for Flutter chat apps, complementing flutter_chat_ui.
  Contains models and core functionality. #chat #ui
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
