name: flutter_chat_core
version: 2.9.0
description: >
  Core package for Flutter chat apps, complementing flutter_chat_ui.
  Contains models and core functionality. #chat #ui
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  intl: ">=0.19.0 <1.0.0"
  json_annotation: ^4.9.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
