name: flutter_chat_core
version: 2.7.0
description: >
  Core package for Flutter chat apps, complementing flutter_chat_ui.
  Contains models and core functionality. #chat #ui
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  intl: '>=0.19.0 <1.0.0'
  json_annotation: ^4.9.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
