name: flyer_chat_file_message
version: 2.4.0
description: >
  File message package for Flutter chat apps, complementing flutter_chat_ui. #chat #ui
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_core: ^2.9.0
  intl: ">=0.19.0 <1.0.0"
  provider: ^6.1.5+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
